title: "PERT Field Guide"
description: "A Practical Introduction to Psychiatric Epidemiology and Population Health Research"

remote_theme: "just-the-docs/just-the-docs"

url: "https://wellsa1-uthscsa.github.io"
baseurl: "/pert-field-guide"

color_scheme: "light"

search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "PERT Field Guide"

mermaid:
  version: "10.9.1"

aux_links:
  "GitHub Repository":
    - "https://github.com/wellsa1-uthscsa/pert-field-guide"

nav_sort: "case_insensitive"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"